// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFKjLL1ZD0hN1_Ooif9612dYxVkhGGwz0',
    appId: '1:506019223926:web:1972afd00a4845d8bf8257',
    messagingSenderId: '506019223926',
    projectId: 'video-app-a3fbf',
    authDomain: 'video-app-a3fbf.firebaseapp.com',
    storageBucket: 'video-app-a3fbf.appspot.com',
    measurementId: 'G-HZP96ED4DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx7HFNJT7xIjEWp8hzYT8p-Z6jvmWTWtQ',
    appId: '1:506019223926:android:1d06c9abad166de2bf8257',
    messagingSenderId: '506019223926',
    projectId: 'video-app-a3fbf',
    storageBucket: 'video-app-a3fbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwdeSU6XtIsHkzxLqKNhRDz_6r9589tWk',
    appId: '1:506019223926:ios:b7cfc03fa5d86f17bf8257',
    messagingSenderId: '506019223926',
    projectId: 'video-app-a3fbf',
    storageBucket: 'video-app-a3fbf.appspot.com',
    iosBundleId: 'com.example.videoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwdeSU6XtIsHkzxLqKNhRDz_6r9589tWk',
    appId: '1:506019223926:ios:b7cfc03fa5d86f17bf8257',
    messagingSenderId: '506019223926',
    projectId: 'video-app-a3fbf',
    storageBucket: 'video-app-a3fbf.appspot.com',
    iosBundleId: 'com.example.videoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFKjLL1ZD0hN1_Ooif9612dYxVkhGGwz0',
    appId: '1:506019223926:web:dafab2a6a3299438bf8257',
    messagingSenderId: '506019223926',
    projectId: 'video-app-a3fbf',
    authDomain: 'video-app-a3fbf.firebaseapp.com',
    storageBucket: 'video-app-a3fbf.appspot.com',
    measurementId: 'G-CSXXPLQZSK',
  );
}
